### ISSUE TITLE
how do i configure mosquitto-exporter ?

### ISSUE THREAD

**Issue by ismaileneskirli** [sapcc/mosquitto-exporter#35]
Thanks for your work, i want to use your repo for my project, how do i configure this repo according to my mqtt broker ? any help is appreciated

**Comment by msrn** [comment]
Somewhat old issue but here's my configuration:

You run the docker image by giving the hostname of your mosquitto broker.  Taken from readme.md

```
docker run --name mosquitto-exporter \
  -p 9234:9234 sapcc/mosquitto-exporter \
  --endpoint tcp://mosquitto:1883
```

Then  you need to configure prometheus.yml with correct scrape configs.

```
scrape_configs:
  - job_name: 'mosquitto-exporter'
    static_configs:
      - targets: ['mosquitto-exporter:9234']
        labels:
         group: 'mosquitto-exporter'
    metrics_path: '/metrics'
    scheme: 'http'
```

This is all assuming you are using docker-compose and/or have created custom bridge network where you can refer to container addresses by their name.

**Comment by msrn** [comment]
Somewhat old issue but here's my configuration:

You run the docker image by giving the hostname of your mosquitto broker.  Taken from readme.md

```
docker run --name mosquitto-exporter \
  -p 9234:9234 sapcc/mosquitto-exporter \
  --endpoint tcp://mosquitto:1883
```

Then  you need to configure prometheus.yml with correct scrape configs.

```
scrape_configs:
  - job_name: 'mosquitto-exporter'
    static_configs:
      - targets: ['mosquitto-exporter:9234']
        labels:
         group: 'mosquitto-exporter'
    metrics_path: '/metrics'
    scheme: 'http'
```
