### ISSUE TITLE
Include example docker-compose.yml file

### ISSUE THREAD

**Issue by ngosang** [sapcc/mosquitto-exporter#43]
My file:
```yml
version: '3.8'

services:

  mosquitto:
    image: eclipse-mosquitto:2.0.14
    container_name: mosquitto
    environment:
      - TZ=Europe/Madrid
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_volume/config:/mosquitto/config
      - mosquitto_volume/data:/mosquitto/data
      - mosquitto_volume/log:/mosquitto/log
    restart: unless-stopped

  mosquitto-exporter:
    image: sapcc/mosquitto-exporter:0.8.0
    container_name: mosquitto-exporter
    command: --endpoint tcp://mosquitto:1883
    environment:
      - TZ=Europe/Madrid
    ports:
      - "9234:9234"
    restart: unless-stopped
```
